"use client";

import { CheckCircle2, LoaderCircle, RotateCcw, SlidersHorizontal, XCircle } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { PravaSDK } from "@prava-sdk/core";

interface Receipt { merchant: string; product: string; amount: string; transactionId: string; timestamp: string; ledgerId: string; }
interface SessionResponse { sessionId: string; sessionToken: string; iframeUrl: string; orderId: string; publishableKey?: string; error?: string; }
const purchase = { merchant: "Vertex Computing", merchantUrl: "https://example.com", product: "NovaForge 15", amount: "$1,059", currency: "USD", decisionLedgerId: "DL-2026-081-01" };

export function ApprovalPanel() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState<string>(); const [receipt, setReceipt] = useState<Receipt>(); const sdk = useRef<PravaSDK | null>(null);
  useEffect(() => () => sdk.current?.destroy(), []);
  const approve = async () => { setLoading(true); setError(undefined); try { const response = await fetch("/api/prava/create-session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(purchase) }); const session = await response.json() as SessionResponse; if (!response.ok || !session.publishableKey) throw new Error(session.error ?? "Prava checkout could not be started."); sdk.current?.destroy(); sdk.current = new PravaSDK({ publishableKey: session.publishableKey }); await sdk.current.collectPAN({ sessionToken: session.sessionToken, iframeUrl: session.iframeUrl, container: "#prava-checkout", onSuccess: (result) => setReceipt({ merchant: purchase.merchant, product: purchase.product, amount: purchase.amount, transactionId: result.enrollmentId || session.orderId, timestamp: new Date().toLocaleString(), ledgerId: purchase.decisionLedgerId }), onError: (pravaError) => setError(pravaError.message), onDismiss: () => setError("Checkout was cancelled.") }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Prava checkout could not be started."); } finally { setLoading(false); } };
  if (receipt) return <section className="rounded-2xl border border-primary/30 bg-primary/5 p-5"><div className="flex items-center gap-2 text-primary"><CheckCircle2 className="size-5" /><p className="text-sm font-semibold uppercase tracking-[0.16em]">Purchase Successful</p></div><h2 className="mt-2 text-xl font-semibold">Trust Receipt</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2">{[["Merchant", receipt.merchant], ["Product", receipt.product], ["Amount", receipt.amount], ["Transaction ID", receipt.transactionId], ["Timestamp", receipt.timestamp], ["Decision Ledger ID", receipt.ledgerId]].map(([label, value]) => <div className="rounded-xl bg-background/50 p-3" key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>)}</div><p className="mt-4 text-sm text-primary">Protected by Prava Sandbox</p><Button className="mt-4" variant="outline"><RotateCcw className="mr-2 size-4" />View Replay</Button></section>;
  return <section className="rounded-2xl border border-primary/25 bg-primary/5 p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Your approval is required</p><h2 className="mt-1 font-semibold">Ready when you are</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">TrustLane will never purchase without your explicit approval.</p><div id="prava-checkout" className="mt-4 min-h-0" />{error && <p className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-4 flex flex-col gap-2 sm:flex-row"><Button disabled={loading} onClick={approve}>{loading ? <LoaderCircle className="mr-2 size-4 animate-spin" /> : <CheckCircle2 className="mr-2 size-4" />}{loading ? "Opening Prava…" : "Approve Purchase"}</Button><Button variant="outline"><SlidersHorizontal className="mr-2 size-4" />Modify Search</Button><Button className="sm:ml-auto" variant="ghost"><XCircle className="mr-2 size-4" />Reject</Button></div></section>;
}
