import type { VerifiedMerchantContext } from "@/services/senso";
import type { CheckoutAttempt, CheckoutLifecycleEvent, HostedCheckoutSession, LatestResearch, LocalPreferences, SavedProduct } from "@/types/dashboard-state";

const keys = { research: "trustlane.latest-research", merchantContext: "trustlane.merchant-context", hostedSession: "trustlane.hosted-checkout", checkoutEmail: "trustlane.checkout-email", checkoutUserId: "trustlane.checkout-user-id", orders: "trustlane.checkout-attempts", saved: "trustlane.saved-products", preferences: "trustlane.preferences" } as const;
const defaults: LocalPreferences = { language: "English", currency: "USD", notifications: true, approvalRequired: true, reducedMotion: false };
function read<T>(key: string, fallback: T): T { if (typeof window === "undefined") return fallback; try { const value = window.localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function write<T>(key: string, value: T) { if (typeof window !== "undefined") { try { window.localStorage.setItem(key, JSON.stringify(value)); } catch { /* Checkout UI remains usable when storage is unavailable. */ } } }
function getOrders(): CheckoutAttempt[] { const value = read<unknown>(keys.orders, []); return Array.isArray(value) ? value as CheckoutAttempt[] : []; }
function sameAttempt(left: CheckoutAttempt, right: Pick<CheckoutAttempt, "id" | "attemptId" | "sessionId">) { return Boolean((right.sessionId && left.sessionId === right.sessionId) || (right.attemptId && left.attemptId === right.attemptId) || left.id === right.id); }
function mergeOrder(attempt: CheckoutAttempt): CheckoutAttempt { const current = getOrders(); const index = current.findIndex((item) => sameAttempt(item, attempt)); const merged = index >= 0 ? { ...current[index], ...attempt, events: attempt.events ?? current[index].events } : attempt; const next = index >= 0 ? current.map((item, itemIndex) => itemIndex === index ? merged : item) : [merged, ...current]; write(keys.orders, next); return merged; }
function updateOrder(identity: { sessionId?: string; attemptId?: string }, changes: Partial<CheckoutAttempt>): CheckoutAttempt | undefined { const current = getOrders(); const index = current.findIndex((item) => Boolean((identity.sessionId && item.sessionId === identity.sessionId) || (identity.attemptId && item.attemptId === identity.attemptId))); if (index < 0) return undefined; const merged = { ...current[index], ...changes }; write(keys.orders, current.map((item, itemIndex) => itemIndex === index ? merged : item)); return merged; }
function addOrderEvent(identity: { sessionId?: string; attemptId?: string }, event: CheckoutLifecycleEvent): CheckoutAttempt | undefined { const current = getOrders(); const target = current.find((item) => Boolean((identity.sessionId && item.sessionId === identity.sessionId) || (identity.attemptId && item.attemptId === identity.attemptId))); if (!target || target.events?.some((item) => item.type === event.type)) return target; return updateOrder(identity, { events: [...(target.events ?? []), event] }); }
function subscribeOrders(listener: (attempts: CheckoutAttempt[]) => void) { if (typeof window === "undefined") return () => undefined; const handler = (event: StorageEvent) => { if (event.key === keys.orders) listener(getOrders()); }; window.addEventListener("storage", handler); return () => window.removeEventListener("storage", handler); }

export const dashboardStorage = { getResearch: () => read<LatestResearch | undefined>(keys.research, undefined), setResearch: (value: LatestResearch) => write(keys.research, value), getMerchantContext: () => read<VerifiedMerchantContext | undefined>(keys.merchantContext, undefined), setMerchantContext: (value: VerifiedMerchantContext) => write(keys.merchantContext, value), getHostedSession: () => read<HostedCheckoutSession | undefined>(keys.hostedSession, undefined), setHostedSession: (value: HostedCheckoutSession) => write(keys.hostedSession, value), getCheckoutEmail: () => read<string>(keys.checkoutEmail, ""), setCheckoutEmail: (value: string) => write(keys.checkoutEmail, value), getCheckoutUserId: () => read<string>(keys.checkoutUserId, ""), setCheckoutUserId: (value: string) => write(keys.checkoutUserId, value), getOrders, setOrders: (value: CheckoutAttempt[]) => write(keys.orders, value), mergeOrder, updateOrder, addOrderEvent, findOrder: (identity: { sessionId?: string; attemptId?: string }) => getOrders().find((item) => Boolean((identity.sessionId && item.sessionId === identity.sessionId) || (identity.attemptId && item.attemptId === identity.attemptId))), subscribeOrders, getSaved: () => read<SavedProduct[]>(keys.saved, []), setSaved: (value: SavedProduct[]) => write(keys.saved, value), getPreferences: () => read<LocalPreferences>(keys.preferences, defaults), setPreferences: (value: LocalPreferences) => write(keys.preferences, value) };
