"use client";

import { CircleAlert, LoaderCircle, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { PaymentVerificationCard, type VerificationReceipt } from "@/components/verification/payment-verification-card";
import { Button } from "@/components/ui/button";
import { dashboardStorage } from "@/lib/dashboard-storage";
import type { HostedCheckoutSession, OrderStatus } from "@/types/dashboard-state";

type ResultStatus = "checking" | "awaiting" | "completed" | "failed" | "pending" | "missing";
export default function HostedCheckoutCompletePage() {
  const [session, setSession] = useState<HostedCheckoutSession>();
  const [status, setStatus] = useState<ResultStatus>("checking");
  const [transactionId, setTransactionId] = useState<string>();
  const [replayOpen, setReplayOpen] = useState(false);
  const check = useCallback(async (active: HostedCheckoutSession) => { setStatus("checking"); try { const response = await fetch("/api/prava/payment-result", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sessionId: active.sessionId }) }); const result = (await response.json()) as { status?: "completed" | "failed" | "pending"; transactionId?: string }; if (!response.ok || !result.status) { setStatus("awaiting"); return; } setTransactionId(result.transactionId); setStatus(result.status); if (result.status === "completed" || result.status === "failed") { const nextStatus: OrderStatus = result.status === "completed" ? "Completed" : "Failed"; dashboardStorage.setOrders(dashboardStorage.getOrders().map((attempt) => attempt.sessionId === active.sessionId ? { ...attempt, status: nextStatus, transactionId: result.transactionId ?? attempt.transactionId } : attempt)); if (result.status === "completed") void fetch("/api/senso/outcome", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ merchant: active.merchant, product: active.product, amount: active.amount, transactionId: result.transactionId ?? active.orderId ?? active.sessionId, ledgerId: active.decisionLedgerId, timestamp: new Date().toLocaleString() }) }); } } catch { setStatus("awaiting"); } }, []);
  useEffect(() => { const active = dashboardStorage.getHostedSession(); setSession(active); if (!active) { setStatus("missing"); return; } void check(active); }, [check]);
  if (status === "missing") return <main className="mx-auto max-w-2xl px-4 py-10"><section className="rounded-2xl border border-border bg-card/60 p-6"><CircleAlert className="size-6 text-amber-300" /><h1 className="mt-3 text-xl font-semibold">Hosted checkout session not found</h1><p className="mt-2 text-sm text-muted-foreground">Return to the approval panel to start a new secure Prava checkout session.</p></section></main>;
  if (!session) return <main className="mx-auto max-w-2xl px-4 py-10"><LoaderCircle className="size-6 animate-spin text-primary" />Checking payment…</main>;
  const receipt: VerificationReceipt = { merchant: session.merchant, product: session.product, amount: session.amount, currency: session.currency, transactionId, pravaSessionId: session.sessionId, timestamp: new Date().toLocaleString(), ledgerId: session.decisionLedgerId, status: "succeeded" };
  return <main className="mx-auto max-w-3xl px-4 py-7 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Prava hosted checkout</p><h1 className="mt-1 text-3xl font-semibold">{status === "checking" ? "Checking payment" : status === "completed" ? "Payment completed" : status === "failed" ? "Payment failed" : status === "pending" ? "Payment pending" : "Awaiting result"}</h1>{status === "completed" ? <><div className="mt-6"><PaymentVerificationCard receipt={receipt} onReplay={() => setReplayOpen((open) => !open)} /></div>{replayOpen && <ol className="mt-5 space-y-3 border-l border-primary/25 pl-5">{["User Request", "AI Research", "Merchant Verification", "Senso Evidence", "Decision Ledger", "User Approval", "Hosted Prava Checkout", "Checkout Result"].map((item, index) => <li className="relative text-sm" key={item}><span className="absolute -left-[29px] grid size-4 place-items-center rounded-full bg-primary text-[9px] text-primary-foreground">{index + 1}</span>{item}</li>)}</ol>}</> : <section className="mt-6 rounded-2xl border border-border bg-card/60 p-6"><p className="text-sm text-muted-foreground">Prava has not returned a confirmed successful payment. This page will not create another session automatically.</p><Button className="mt-5" onClick={() => void check(session)} variant="outline"><RefreshCw className="mr-2 size-4" />Check payment result</Button></section>}</main>;
}
